default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: soter_dev

test:
  <<: *default
  database: soter_test

production:
  <<: *default
  database: app_production